# Example Buildkite Pipeline for Multi-GPU Testing
# Copy this to your project at .buildkite/pipeline.yml and customize

steps:
  - label: ":nvidia: Build & Test - V100"
    command: |
      # Commands run inside Slurm job via enroot/pyxis
      srun --container-image=/path/to/base-v100.sqsh \
           --container-mounts=${BUILDKITE_BUILD_CHECKOUT_PATH}:/workspace \
           --container-workdir=/workspace \
           bash -c "
             cmake -B build -S . \
               -DCMAKE_BUILD_TYPE=Release \
               -DCMAKE_CUDA_ARCHITECTURES=70 &&
             cmake --build build -j\$(nproc) &&
             ctest --test-dir build --output-on-failure
           "
    env:
      BUILDKITE_PLUGIN_GPU_ARCH: "v100"
    agents:
      queue: "your-cluster-name"  # Use your cluster name or "*" for any cluster
      slurm: "true"

  - label: ":amd: Build & Test - MI210"
    command: |
      srun --container-image=/path/to/base-mi210.sqsh \
           --container-mounts=${BUILDKITE_BUILD_CHECKOUT_PATH}:/workspace \
           --container-workdir=/workspace \
           bash -c "
             cmake -B build -S . \
               -DCMAKE_BUILD_TYPE=Release \
               -DCMAKE_HIP_ARCHITECTURES=gfx90a &&
             cmake --build build -j\$(nproc) &&
             ctest --test-dir build --output-on-failure
           "
    env:
      BUILDKITE_PLUGIN_GPU_ARCH: "mi210"
    agents:
      queue: "your-cluster-name"  # Use your cluster name or "*" for any cluster
      slurm: "true"

  - label: ":amd: Build & Test - MI300A"
    command: |
      srun --container-image=/path/to/base-mi300a.sqsh \
           --container-mounts=${BUILDKITE_BUILD_CHECKOUT_PATH}:/workspace \
           --container-workdir=/workspace \
           bash -c "
             cmake -B build -S . \
               -DCMAKE_BUILD_TYPE=Release \
               -DCMAKE_HIP_ARCHITECTURES=gfx942 &&
             cmake --build build -j\$(nproc) &&
             ctest --test-dir build --output-on-failure
           "
    env:
      BUILDKITE_PLUGIN_GPU_ARCH: "mi300a"
    agents:
      queue: "your-cluster-name"  # Use your cluster name or "*" for any cluster
      slurm: "true"

  # Optional: Upload test results as artifacts
  - wait
  
  - label: ":package: Collect Artifacts"
    command: |
      buildkite-agent artifact upload "build/Testing/**/*"
    agents:
      queue: "gpu"
